### PR TITLE
Make changes to the SonarCloud settings

### PR DESCRIPTION
**Pull request by patdnr**

### CODE REVIEW

**Comment by patdnr** [comment]
Utilizing Coverlet by the commands below would only produce code coverage in the src/Domain/ directory.
```
coverlet .\artifacts\DomainTests\bin\Debug\net6.0\DomainTests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage/DomainTests.xml"
coverlet .\artifacts\DomainTests\bin\Debug\net6.0\IntegrationTests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage/IntegrationTests.xml"
coverlet .\artifacts\DomainTests\bin\Debug\net6.0\LocalRepositoryTests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage/LocalRepositoryTests.xml"
coverlet .\artifacts\DomainTests\bin\Debug\net6.0\WebAppTests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage/WebAppTests.xml"
```
image

Switching to using `dotnet test --collect:"XPlat Code Coverage"`

**Comment by patdnr** [comment]
Got the code coverage working! However, the percentage is different from ReportGenerator HTML 

image

ReportGenerator HTML:
image

**Comment by patdnr** [comment]
See gaepdit/EPD-IT#82

**Review by dougwaldron — APPROVED** [review]
Great work! I tweaked the coverlet commands to get merging to work.

**Pull request merged**
